// This file is @generated by prost-build.
#[actix_prost_macros::serde]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorRequest {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[actix_prost_macros::serde]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ErrorResponse {}
pub mod errors_rpc_actix {
    #![allow(unused_variables, dead_code, missing_docs)]
    use super::*;
    use super::errors_rpc_server::ErrorsRpc;
    use std::sync::Arc;
    use actix_web::Responder;
    #[derive(Clone, PartialEq, ::prost::Message)]
    #[actix_prost_macros::serde(rename_all = "snake_case")]
    pub struct ErrorPath {
        #[prost(int32, tag = "1")]
        pub code: i32,
    }
    #[actix_prost_macros::serde]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ErrorQuery {
        #[prost(string, tag = "2")]
        pub query: ::prost::alloc::string::String,
    }
    #[actix_prost_macros::serde]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ErrorJson {
        #[prost(string, tag = "3")]
        pub message: ::prost::alloc::string::String,
    }
    async fn call_error(
        service: ::actix_web::web::Data<dyn ErrorsRpc + Sync + Send + 'static>,
        http_request: ::actix_web::HttpRequest,
        payload: ::actix_web::web::Payload,
    ) -> Result<impl Responder, ::actix_prost::Error> {
        let mut payload = payload.into_inner();
        let path = <::actix_web::web::Path<
            ErrorPath,
        > as ::actix_web::FromRequest>::extract(&http_request)
            .await
            .map_err(|err| ::actix_prost::Error::from_actix(
                err,
                ::tonic::Code::InvalidArgument,
            ))?
            .into_inner();
        let query = <::actix_web::web::Query<
            ErrorQuery,
        > as ::actix_web::FromRequest>::extract(&http_request)
            .await
            .map_err(|err| ::actix_prost::Error::from_actix(
                err,
                ::tonic::Code::InvalidArgument,
            ))?
            .into_inner();
        let json = <::actix_web::web::Json<
            ErrorJson,
        > as ::actix_web::FromRequest>::from_request(&http_request, &mut payload)
            .await
            .map_err(|err| ::actix_prost::Error::from_actix(
                err,
                ::tonic::Code::InvalidArgument,
            ))?
            .into_inner();
        let request = ErrorRequest {
            code: path.code,
            query: query.query,
            message: json.message,
        };
        let request = ::actix_prost::new_request(request, &http_request);
        let response = service.error(request).await?;
        let headers = response.metadata().clone().into_headers();
        let response = response.into_inner();
        let mut json_response = ::actix_web::web::Json(response).customize();
        for (key, value) in headers.iter() {
            json_response = json_response
                .insert_header((key.as_str(), value.as_bytes()));
        }
        Ok(json_response)
    }
    pub fn route_errors_rpc(
        config: &mut ::actix_web::web::ServiceConfig,
        service: Arc<dyn ErrorsRpc + Send + Sync + 'static>,
    ) {
        config.app_data(::actix_web::web::Data::from(service));
        config.route("/errors/{code}", ::actix_web::web::post().to(call_error));
    }
}
#[derive(Clone, Debug)]
pub struct ErrorRequestInternal {
    pub code: i32,
    pub query: ::prost::alloc::string::String,
    pub message: ::prost::alloc::string::String,
}
impl convert_trait::TryConvert<ErrorRequest> for ErrorRequestInternal {
    fn try_convert(from: ErrorRequest) -> Result<Self, String> {
        Ok(Self {
            code: from.code,
            query: from.query,
            message: from.message,
        })
    }
}
#[derive(Clone, Debug)]
pub struct ErrorResponseInternal {}
impl convert_trait::TryConvert<ErrorResponseInternal> for ErrorResponse {
    fn try_convert(_from: ErrorResponseInternal) -> Result<Self, String> {
        Ok(Self {})
    }
}
/// Generated client implementations.
pub mod errors_rpc_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ErrorsRpcClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ErrorsRpcClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ErrorsRpcClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ErrorsRpcClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ErrorsRpcClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn error(
            &mut self,
            request: impl tonic::IntoRequest<super::ErrorRequest>,
        ) -> std::result::Result<tonic::Response<super::ErrorResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/errors.ErrorsRPC/Error");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("errors.ErrorsRPC", "Error"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod errors_rpc_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ErrorsRpcServer.
    #[async_trait]
    pub trait ErrorsRpc: std::marker::Send + std::marker::Sync + 'static {
        async fn error(
            &self,
            request: tonic::Request<super::ErrorRequest>,
        ) -> std::result::Result<tonic::Response<super::ErrorResponse>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct ErrorsRpcServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ErrorsRpcServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ErrorsRpcServer<T>
    where
        T: ErrorsRpc,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/errors.ErrorsRPC/Error" => {
                    #[allow(non_camel_case_types)]
                    struct ErrorSvc<T: ErrorsRpc>(pub Arc<T>);
                    impl<T: ErrorsRpc> tonic::server::UnaryService<super::ErrorRequest>
                    for ErrorSvc<T> {
                        type Response = super::ErrorResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ErrorRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ErrorsRpc>::error(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ErrorSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ErrorsRpcServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "errors.ErrorsRPC";
    impl<T> tonic::server::NamedService for ErrorsRpcServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
