// This file is @generated by prost-build.
#[actix_prost_macros::serde]
#[actix_prost_macros::serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SimpleMessages {
    #[prost(int64, tag = "1")]
    pub long_name_field: i64,
}
#[actix_prost_macros::serde]
#[actix_prost_macros::serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OneOfs {
    #[prost(oneof = "one_ofs::SnakeCaseValues", tags = "1, 2")]
    pub snake_case_values: ::core::option::Option<one_ofs::SnakeCaseValues>,
}
/// Nested message and enum types in `OneOfs`.
pub mod one_ofs {
    #[actix_prost_macros::serde]
    #[actix_prost_macros::serde(rename_all = "snake_case")]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum SnakeCaseValues {
        #[prost(int64, tag = "1")]
        FirstSnakeCaseValue(i64),
        #[prost(int64, tag = "2")]
        SecondSnakeCaseValue(i64),
    }
}
pub mod snake_case_types_rpc_actix {
    #![allow(unused_variables, dead_code, missing_docs)]
    use super::*;
    use super::snake_case_types_rpc_server::SnakeCaseTypesRpc;
    use std::sync::Arc;
    #[actix_prost_macros::serde]
    #[actix_prost_macros::serde(rename_all = "snake_case")]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct SimpleMessagesRPCJson {
        #[prost(int64, tag = "1")]
        pub long_name_field: i64,
    }
    #[actix_prost_macros::serde]
    #[actix_prost_macros::serde(rename_all = "snake_case")]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct OneOfsRPCJson {
        #[prost(oneof = "one_ofs::SnakeCaseValues", tags = "1, 2")]
        pub snake_case_values: ::core::option::Option<one_ofs::SnakeCaseValues>,
    }
    async fn call_simple_messages_rpc(
        service: ::actix_web::web::Data<dyn SnakeCaseTypesRpc + Sync + Send + 'static>,
        http_request: ::actix_web::HttpRequest,
        payload: ::actix_web::web::Payload,
    ) -> Result<::actix_web::web::Json<SimpleMessages>, ::actix_prost::Error> {
        let mut payload = payload.into_inner();
        let json = <::actix_web::web::Json<
            SimpleMessagesRPCJson,
        > as ::actix_web::FromRequest>::from_request(&http_request, &mut payload)
            .await
            .map_err(|err| ::actix_prost::Error::from_actix(
                err,
                ::tonic::Code::InvalidArgument,
            ))?
            .into_inner();
        let request = SimpleMessages {
            long_name_field: json.long_name_field,
        };
        let request = ::actix_prost::new_request(request, &http_request);
        let response = service.simple_messages_rpc(request).await?;
        let response = response.into_inner();
        Ok(::actix_web::web::Json(response))
    }
    async fn call_one_ofs_rpc(
        service: ::actix_web::web::Data<dyn SnakeCaseTypesRpc + Sync + Send + 'static>,
        http_request: ::actix_web::HttpRequest,
        payload: ::actix_web::web::Payload,
    ) -> Result<::actix_web::web::Json<OneOfs>, ::actix_prost::Error> {
        let mut payload = payload.into_inner();
        let json = <::actix_web::web::Json<
            OneOfsRPCJson,
        > as ::actix_web::FromRequest>::from_request(&http_request, &mut payload)
            .await
            .map_err(|err| ::actix_prost::Error::from_actix(
                err,
                ::tonic::Code::InvalidArgument,
            ))?
            .into_inner();
        let request = OneOfs {
            snake_case_values: json.snake_case_values,
        };
        let request = ::actix_prost::new_request(request, &http_request);
        let response = service.one_ofs_rpc(request).await?;
        let response = response.into_inner();
        Ok(::actix_web::web::Json(response))
    }
    pub fn route_snake_case_types_rpc(
        config: &mut ::actix_web::web::ServiceConfig,
        service: Arc<dyn SnakeCaseTypesRpc + Send + Sync + 'static>,
    ) {
        config.app_data(::actix_web::web::Data::from(service));
        config
            .route(
                "/snake-case-types/simple-messages",
                ::actix_web::web::post().to(call_simple_messages_rpc),
            );
        config
            .route(
                "/snake-case-types/oneofs",
                ::actix_web::web::post().to(call_one_ofs_rpc),
            );
    }
}
#[derive(Clone, Debug)]
pub struct SimpleMessagesInternal {
    pub long_name_field: i64,
}
impl convert_trait::TryConvert<SimpleMessages> for SimpleMessagesInternal {
    fn try_convert(from: SimpleMessages) -> Result<Self, String> {
        Ok(Self {
            long_name_field: from.long_name_field,
        })
    }
}
impl convert_trait::TryConvert<SimpleMessagesInternal> for SimpleMessages {
    fn try_convert(from: SimpleMessagesInternal) -> Result<Self, String> {
        Ok(Self {
            long_name_field: from.long_name_field,
        })
    }
}
#[derive(Clone, Debug)]
pub struct OneOfsInternal {
    pub snake_case_values: ::core::option::Option<one_ofs::SnakeCaseValues>,
}
impl convert_trait::TryConvert<OneOfs> for OneOfsInternal {
    fn try_convert(from: OneOfs) -> Result<Self, String> {
        Ok(Self {
            snake_case_values: from.snake_case_values,
        })
    }
}
impl convert_trait::TryConvert<OneOfsInternal> for OneOfs {
    fn try_convert(from: OneOfsInternal) -> Result<Self, String> {
        Ok(Self {
            snake_case_values: from.snake_case_values,
        })
    }
}
/// Generated client implementations.
pub mod snake_case_types_rpc_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SnakeCaseTypesRpcClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SnakeCaseTypesRpcClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SnakeCaseTypesRpcClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SnakeCaseTypesRpcClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SnakeCaseTypesRpcClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn simple_messages_rpc(
            &mut self,
            request: impl tonic::IntoRequest<super::SimpleMessages>,
        ) -> std::result::Result<tonic::Response<super::SimpleMessages>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snake_case_types.SnakeCaseTypesRPC/SimpleMessagesRPC",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "snake_case_types.SnakeCaseTypesRPC",
                        "SimpleMessagesRPC",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn one_ofs_rpc(
            &mut self,
            request: impl tonic::IntoRequest<super::OneOfs>,
        ) -> std::result::Result<tonic::Response<super::OneOfs>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snake_case_types.SnakeCaseTypesRPC/OneOfsRPC",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("snake_case_types.SnakeCaseTypesRPC", "OneOfsRPC"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod snake_case_types_rpc_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SnakeCaseTypesRpcServer.
    #[async_trait]
    pub trait SnakeCaseTypesRpc: std::marker::Send + std::marker::Sync + 'static {
        async fn simple_messages_rpc(
            &self,
            request: tonic::Request<super::SimpleMessages>,
        ) -> std::result::Result<tonic::Response<super::SimpleMessages>, tonic::Status>;
        async fn one_ofs_rpc(
            &self,
            request: tonic::Request<super::OneOfs>,
        ) -> std::result::Result<tonic::Response<super::OneOfs>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct SnakeCaseTypesRpcServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SnakeCaseTypesRpcServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SnakeCaseTypesRpcServer<T>
    where
        T: SnakeCaseTypesRpc,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snake_case_types.SnakeCaseTypesRPC/SimpleMessagesRPC" => {
                    #[allow(non_camel_case_types)]
                    struct SimpleMessagesRPCSvc<T: SnakeCaseTypesRpc>(pub Arc<T>);
                    impl<
                        T: SnakeCaseTypesRpc,
                    > tonic::server::UnaryService<super::SimpleMessages>
                    for SimpleMessagesRPCSvc<T> {
                        type Response = super::SimpleMessages;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SimpleMessages>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SnakeCaseTypesRpc>::simple_messages_rpc(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SimpleMessagesRPCSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snake_case_types.SnakeCaseTypesRPC/OneOfsRPC" => {
                    #[allow(non_camel_case_types)]
                    struct OneOfsRPCSvc<T: SnakeCaseTypesRpc>(pub Arc<T>);
                    impl<T: SnakeCaseTypesRpc> tonic::server::UnaryService<super::OneOfs>
                    for OneOfsRPCSvc<T> {
                        type Response = super::OneOfs;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OneOfs>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as SnakeCaseTypesRpc>::one_ofs_rpc(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = OneOfsRPCSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SnakeCaseTypesRpcServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snake_case_types.SnakeCaseTypesRPC";
    impl<T> tonic::server::NamedService for SnakeCaseTypesRpcServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
