[package]
name = "actix-prost-build"
version = "0.1.0"
edition = "2021"

[dependencies]
convert-trait = { path = "../convert-trait", optional = true}
thiserror = "1.0"
proc-macro2 = "1.0"
prost-build = "0.11"
prettyplease = "0.2"
prost-reflect = "0.12.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

[features]
conversions = ["dep:convert-trait"]