[package]
name = "actix-prost-build"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
proc-macro2 = "1.0"
prost-build = "0.11"
prettyplease = "0.1"
prost-reflect = "0.12.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
