[package]
name = "actix-prost-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
proc-macro2 = "1.0"
prost-build = "0.11"
prettyplease = "0.1"
quote = "1.0"
itertools = "0.10"
syn = { version = "1.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
