[package]
name = "actix-prost-macros"
version = "2.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = [ "extra-traits", "full" ] }
quote = "1.0"
