[package]
name = "actix-prost"
version = "2.0.0"
edition = "2021"

[dependencies]
http = "1.2"
tonic = "0.12"
actix-web = "4"
actix-http = "3"
serde = { version = "1", features = [ "derive" ] }
serde_with = { version = "3.12", features = [ "base64" ] }
prost = "0.13"
serde_json = "1.0"
